const games = [
    {
        id: 1,
        venue: "Sydney Harbour Sports Ground",
        time: "09:00",
        date: "28/06/24",
        gender: "Male",
        privacy: "open",
        spots: "11/12",
        host: "theowalcot6",
        a_side: 6,
        currency: '$',
        cost: 2.50,
        description: "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum ",
        owner: "theowalcot6",
        longitude: 151.2210,
        latitude: -33.8523
    },
    {
        id: 2,
        venue: "Bondi Beach Sports Complex",
        time: "10:00",
        date: "28/06/24",
        gender: "Female",
        privacy: "open",
        spots: "8/10",
        host: "sarahjones7",
        a_side: 5,
        currency: '$',
        cost: 3.00,
        description: "Lorem ipsum",
        owner: "sarahjones7",
        longitude: 151.2743,
        latitude: -33.8908
    },
    {
        id: 3,
        venue: "Centennial Park",
        time: "11:00",
        date: "29/06/24",
        gender: "Mixed",
        privacy: "closed",
        spots: "5/6",
        host: "matthewsmith8",
        a_side: 3,
        currency: '$',
        cost: 4.00,
        description: "Lorem ipsum",
        owner: "matthewsmith8",
        longitude: 151.2432,
        latitude: -33.8977
    },
    {
        id: 4,
        venue: "Sydney Olympic Park",
        time: "12:00",
        date: "30/06/24",
        gender: "Male",
        privacy: "open",
        spots: "10/12",
        host: "johnwick9",
        a_side: 6,
        currency: '$',
        cost: 2.50,
        description: "Lorem ipsum",
        owner: "johnwick9",
        longitude: 151.0634,
        latitude: -33.8450
    },
    {
        id: 5,
        venue: "Moore Park",
        time: "13:00",
        date: "01/07/24",
        gender: "Female",
        privacy: "closed",
        spots: "6/8",
        host: "emilyclark10",
        a_side: 4,
        currency: '$',
        cost: 3.50,
        description: "Lorem ipsum",
        owner: "emilyclark10",
        longitude: 151.2195,
        latitude: -33.8895
    },
    {
        id: 6,
        venue: "Waverley Park",
        time: "14:00",
        date: "02/07/24",
        gender: "Mixed",
        privacy: "open",
        spots: "12/14",
        host: "davidmiller11",
        a_side: 7,
        currency: '$',
        cost: 5.00,
        description: "Lorem ipsum",
        owner: "davidmiller11",
        longitude: 151.2632,
        latitude: -33.9000
    },
    {
        id: 7,
        venue: "Leichhardt Oval",
        time: "15:00",
        date: "03/07/24",
        gender: "Male",
        privacy: "closed",
        spots: "9/10",
        host: "bradpitt12",
        a_side: 5,
        currency: '$',
        cost: 2.00,
        description: "Lorem ipsum",
        owner: "bradpitt12",
        longitude: 151.1527,
        latitude: -33.8637
    },
]


export default games;
